#!/bin/bash

DIRECTION=$1
PANES="$(tmux display-message -p '#{window_panes}')"

if [ $PANES -gt 1 ]
then
  if [ $DIRECTION == "Close" ]
  then
    tmux kill-pane
  fi
fi

if [ $PANES -eq 1 ]
then
  if [ $DIRECTION == "Up" ]
  then
    tmux split-window -h
    exit 0
  fi
fi

if [ $PANES -eq 2 ]
then
  if [ $DIRECTION == "Up" ]
  then
    tmux select-pane -t 1
    tmux split-window -v
    exit 0
  fi
fi
