#!/bin/bash

DIRECTION=$1
PANES="$(tmux display-message -p '#{window_panes}')"

if [ $DIRECTION == "Up" ]
then
  tmux resize-pane -Z
  exit 0
fi

if [ $PANES -eq 3 ]
then
  if [ $DIRECTION == "Right" ]
  then
    tmux select-pane -t 1
    exit 0
  fi
  if [ $DIRECTION == "Left" ]
  then
    tmux select-pane -t 0
    exit 0
  fi
fi

if [ $PANES -eq 1 ]
then
  if [ $DIRECTION == "Right" ]
  then
    tmux split-window -h
  fi
fi
